"use client";

import Link from "next/link";
import { useSessionStore } from "@/frontend/state/sessionStore";

export function HrDashboard() {
  const { profile, skillProfile, match, decisions } = useSessionStore();
  return <><section className="hero dashboard-hero"><div><p className="eyebrow">HR workspace</p><h1>See capability before familiarity.</h1><p>Compare one candidate with one role using evidence-backed skill matches. You—not the system—make and record the decision.</p><div className="hero-actions"><Link className="primary" href="/review">Create skill match</Link><Link className="secondary" href="/candidate">View candidate portal</Link></div></div><div className="persona-chip hr"><span>Recruiter</span><strong>Human review required</strong><small>No automated hiring action</small></div></section><div className="metric-grid"><Metric label="Candidate profile" value={profile && skillProfile ? "Available" : "Waiting"}/><Metric label="Match analysis" value={match ? "Created" : "Not created"}/><Metric label="Decision events" value={String(decisions.length)}/></div><div className="grid two"><section className="card"><div className="section-head"><h2>Review queue</h2><span>Single-session demo</span></div>{profile ? <div className="candidate-row"><div className="avatar">{profile.name.value?.slice(0,1) ?? "C"}</div><div><strong>{profile.name.value}</strong><span>{profile.roles[0]?.title.value} · {profile.roles[0]?.country.value}</span></div><Link href="/review">Review →</Link></div> : <div className="empty-state"><strong>No confirmed candidate yet</strong><p>Complete the Candidate profile first, then return here for matching.</p><Link className="secondary" href="/profile">Create demo profile</Link></div>}</section><section className="card"><p className="eyebrow">Decision policy</p><h2>Explain, then let a person decide.</h2><ul className="check-list"><li>One result for every JD-required skill</li><li>Source evidence and plain-language rationale</li><li>Low match when candidate evidence is absent</li><li>Append-only recruiter decision history</li></ul></section></div></>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
