"use client";

import Link from "next/link";
import { useSessionStore } from "@/frontend/state/sessionStore";

export function CandidateDashboard() {
  const { profile, skillProfile, gaps } = useSessionStore();
  const skillCount = skillProfile?.groups.reduce((total, group) => total + group.skills.length, 0) ?? 0;
  return <><section className="hero dashboard-hero"><div><p className="eyebrow">Candidate portal</p><h1>Turn lived experience into visible capability.</h1><p>Review what was extracted, confirm what is true, and see how your skills transfer—without being reduced to a score.</p><div className="hero-actions"><Link className="primary" href="/profile">{profile ? "Review my profile" : "Build my profile"}</Link>{skillProfile && <Link className="secondary" href="/skills">View translated skills</Link>}</div></div><div className="persona-chip"><span>Candidate</span><strong>{profile?.name.value ?? "Minh Tran"}</strong><small>{profile ? `Profile revision ${profile.revision}` : "No profile created yet"}</small></div></section><div className="metric-grid"><Metric label="Profile" value={profile ? "Ready" : "Not started"} tone={profile ? "good" : "warm"}/><Metric label="Visible skills" value={String(skillCount)} tone="good"/><Metric label="Honest gaps" value={String(gaps?.gaps.length ?? 0)} tone="warm"/></div><div className="grid two"><section className="card"><p className="eyebrow">Your journey</p><h2>Three transparent steps</h2><ol className="journey"><li className={profile ? "done" : "current"}><b>1</b><div><strong>Build and confirm profile</strong><span>You approve ambiguous or edited information.</span></div></li><li className={skillProfile ? "done" : profile ? "current" : ""}><b>2</b><div><strong>Translate transferable skills</strong><span>Every mapping includes source evidence and a reason.</span></div></li><li><b>3</b><div><strong>Share for human review</strong><span>HR sees per-skill evidence, never an overall score.</span></div></li></ol></section><section className="card soft-card"><p className="eyebrow">Privacy promise</p><h2>You stay in control.</h2><p>Only synthetic or consented CV data belongs in this prototype. Your profile remains in this local browser session and the app has no production database.</p><div className="callout">AI suggestions are drafts until a human confirms them.</div></section></div></>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: string }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>; }
